#!/bin/bash
[ "$#" -eq 2 ] || echo "Usage: zcp <codebase> <name>"
[ "$#" -eq 2 ] || exit 1

echo updating base project...
pushd ~/z/hg/$1 > /dev/null
zhg pull -u
popd > /dev/null

echo copying project...
cp -R ~/z/hg/$1 $2
