#!/bin/bash

level=$(cat ~/z/current/server/.hg/hgrc | grep hg-repo | cut -d "/" -f 5)
echo $level

pushd ~/z
pushd hg/$level
zhg pull -u
popd
pushd current
zhg pull -u
popd
#diffmerge --nosplash --title1="hg" --title2="proj" hg/$level current
vim -f '+next' '+execute "DirDiff" fnameescape(argv(0)) fnameescape(argv(1))' "hg/$level" "current"
popd
