#!/bin/bash
set -e  # Fail on error
[ "$#" -eq 2 ] || echo "Usage: zproj <codebase> <name>"
[ "$#" -eq 2 ] || exit 1


if [ -d "~/z/proj/$2" ]; then
    exit 2
fi

pushd ~/z/proj
zcp $1 $1-$2
zswitch $1-$2
popd
zvi
