#!/bin/bash
[ "$#" -eq 1 ] || echo "Usage: zpull name"
[ "$#" -eq 1 ] || exit 1

for proj in "proj" "proj-prist"
do
    echo "$proj:"
    for dir in ~/z/$proj/$1/*
    do
        if [ -d "$dir" ]; then
            echo -e "\t$dir"
            pushd $dir > /dev/null
            hg pull --quiet
            hg update --quiet
            popd > /dev/null
        fi
    done
done
